### ISSUE TITLE
Initialize a bunch of variables at once

### ISSUE THREAD

**Issue by tobyink** [cxw42/Perl-vars-i#6]
Seems something like this should be pretty easy to support:

```
use vars::i {
   '$foo' => 1,
   '@bar' => ['a' .. 'z'],
   '%baz' => { quux => 'xyzzy' },
};
```

**Comment by cxw42** [comment]
I agree --- and as of v2.000000, that should actually work! :)  https://metacpan.org/release/vars-i/source/lib/vars/i.pm#L30  Does the code in your comment fail using the latest release in your testing?  If so, it's definitely a bug.

Thanks for reporting!  Let me know if you have an MCVE for code, or if it's an omission in the docs.

**Comment by tobyink** [comment]
I must have missed that!
